# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Xuduoduo's Blog
tagline:          'Xuduoduo'
description:      'News, articles and reviews of a variety of web development frameworks and modules.'
url:              http://xuduoduo.me
baseurl:          /

author:
  name:           'xuduoduo'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
  
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
